// Generated by Ludicord. Changes will be replaced by ludicord dev or ludicord build.
import "ludicord/navigation";

declare module "ludicord/navigation" {
  interface LudicordRouteRegistry {
    readonly prefix: "/";
    readonly pagePattern: "/";
    readonly pageParams: {
      readonly "/": Readonly<Record<string, never>>;
    };
    readonly embed: "home" | "me";
    readonly embedPattern: "home" | "me";
    readonly embedsByPrefix: {
      readonly "/": "home" | "me";
    };
    readonly api: "/api/hello";
    readonly websocket: "/ws/audience";
    readonly embedParams: {
      readonly "home": Readonly<Record<string, never>>;
      readonly "me": Readonly<Record<string, never>>;
    };
    readonly apiParams: {
      readonly "/api/hello": Readonly<Record<string, never>>;
    };
    readonly websocketParams: {
      readonly "/ws/audience": Readonly<Record<string, never>>;
    };
    readonly config: {
      readonly defaultEmbed: "home";
      readonly outsideDiscord: "allow";
      readonly authRequired: true;
      readonly strictMode: true;
      readonly clientAssetWarningLimit: 512000;
    };
  }
}
